function [rowidx colidx entrices] = matr(n,t,h)
r=t/(h)^2;
rowidx = zeros(1,n^2+1);
rowidx(1) = 1;
colidx = [];
entrices = [];
temp = 0;
for j = 1:n
    colidx(2*j-1) = j;
    entrices(2*j-1) = r;
    colidx(2*j) = j + n;
    entrices(2*j) = -r;
    rowidx(j+1) = 2 * j + 1;
    temp = temp + 2;
end
for i = 2:n-1
    colidx(temp+1) = (i-1) * n + 1;
    entrices(temp+1) = r;
    colidx(temp+2) = (i-1) * n + 2;
    entrices(temp+2) = -r;
    temp = temp + 2;
    rowidx((i-1)*n+2) = temp + 1;
    for k = 2:n-1
        colidx(temp+1) = (i-2) * n + k;
        entrices(temp+1) = -r;
        colidx(temp+2) = (i-1) * n + k - 1;
        entrices(temp+2) = -r;
        colidx(temp+3) = (i-1) * n + k;
        entrices(temp+3) = 1 + 4 * r;
        colidx(temp+4) = (i-1) * n + k + 1;
        entrices(temp+4) = -r;
        colidx(temp+5) = i * n + k;
        entrices(temp+5) = -r;
        temp = temp + 5;
        rowidx((i-1)*n+k+1) = temp + 1;
    end
    colidx(temp+1) = i * n - 1;
    entrices(temp+1) = -r;
    colidx(temp+2) = i * n;
    entrices(temp+2) = r;
    temp = temp + 2;
    rowidx(i*n+1) = temp + 1;
end
for j = 1:n
    colidx(temp+1) = n^2 - 2 * n + j;
    entrices(temp+1) = r;
    colidx(temp+2) = n^2 - n + j;
    entrices(temp+2) = -r;
    rowidx(n^2-n+j+1) = rowidx(n^2-n+1) + 2 * j;
    temp = temp + 2;
end
rowidx(end) = temp;